config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/project'
  get 'static_pages/about'
  get 'static_pages/resume'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#home"
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w.%+\-]+)@([\w\-]+\.)+(\w{2,})\z/i
  attribute :message, validate: true
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: 'Contact Form Inquiry',
      to: 'lafontant.david@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def thanks; end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
      redirect_to contacts_thanks_url
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'json'

  def project
    @profile_data = JSON.parse(File.read('app/assets/javascripts/data.json'))
    @profile_data = @profile_data['data']['repositoryOwner']['itemShowcase']['items']['edges']

    @profile_data
  end

  def about; end

  def home; end

  def resume
    send_file "#{Rails.root}/app/assets/docs/Resume.pdf", type: 'application/pdf', x_sendfile: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>
  <h3>Thank you for your message!</h3>
  <h3>Get back to you soon</h3>
</div>

app/views/contacts/new.html.erb
<div class="hero min-h-screen">
  <div class="hero-content flex-col lg:flex-row-reverse">
    <div class="text-center lg:text-left text-white">
      <h1 class="text-5xl font-bold">Get in touch!</h1>
      <p class="py-6">I am here to build your web application and grow your business!</p>
      <ul>
        <li class="btn gap-2">
          <a href="mailto:lafontant.david@gmail.com" title="link to send an email to david lafontant">lafontant.david@gmail.com</a></li>
        </li>
        <li class="btn gap-2">
          <a href="tel:+8097599396" title="link to call david lafontant">+8097599396</a>
        </li>
      </ul>
    </div>
    <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-uranian_blue">
      <div class="card-body">
       <%= form_for @contact do |f| %>
          <div class="form-control">
            <label class="label">
              <span class="label-text text-site_dark_blue"> <%= f.label :name %></span>
            </label>
            <%= f.text_field  :name, required: true, :class => "input input-bordered", placeholder: "Enter your name please" %>
          </div>
          <div class="form-control">
            <label class="label">
              <span class="label-text text-site_dark_blue"> <%= f.label :email %></span>
            </label>
            <%= f.text_field :email, required: true, class: "input input-bordered", placeholder: "Enter your email please" %>
          </div>
          
          <div class="form-control">
            <label class="label">
              <span class="label-text text-site_dark_blue"> <%= f.label :message %></span>
            </label>
            <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "textarea textarea-bordered h-24 text-white", 
            placeholder: "Send me a message"%><br>
          </div>

      <div class= "d-none hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>


        <div class="form-control mt-6">
          <button class="btn btn-primary">
       <%= f.submit 'Send Message' %>
          
          
          </button>
                
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/thanks.html.erb
<div class="w-full md:w-96 md:max-w-full mx-auto">
  <div class="card w-96 glass">
  <figure>
  
  <%= image_tag("pexels-rakicevic-nenad-1262304.jpg", alt: "Message sent") %>
  
</figure>
  <div class="card-body">
    <h2 class="card-title">Thank you for your message!</h2>
    <p>Get back to you soon!</p>
    <div class="card-actions justify-end">
    </div>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
 <div class="glass" id="footer">

    <ul id="social">
      <li>
        <a href="https://www.linkedin.com/in/david-lafontant/" title="Linkedin profile page of David Lafontant" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/></svg>
        </a>
      </li>
      <li>     
        <a href="https://github.com/david-lafontant" title="Github profile page of David Lafontant" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
        </a>
      </li>
      <li>
        <a href="https://wa.me/18097599396" title="link to contact me on WhatsApp" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 59.7 94.8 83.8 35.2 15.2 49 16.5 66.6 13.9 10.7-1.6 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z"/></svg>
        </a>
      </li>
      <li>
        <a href="mailto:lafontant.david@gmail.com" title="link to send an email to david lafontant" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5"><g fill="currentColor"  fill-rule="evenodd"><g fill-rule="nonzero"><path d="M34.91 448.818h81.454V251L0 163.727V413.91c0 19.287 15.622 34.91 34.91 34.91z" fill="currentColor" /><path d="M395.636 448.818h81.455c19.287 0 34.909-15.622 34.909-34.909V163.727L395.636 251z" fill="currentColor" /><path d="M395.636 99.727V251L512 163.727v-46.545c0-43.142-49.25-67.782-83.782-41.891z" fill="currentColor" /></g><path d="M116.364 251V99.727L256 204.455 395.636 99.727V251L256 355.727z" fill="currentColor" /><path d="M0 117.182v46.545L116.364 251V99.727L83.782 75.291C49.25 49.4 0 74.04 0 117.18z" fill="currentColor"  fill-rule="nonzero"/></g></svg>
        </a>
      </li>
      <li>
        <a href="https://twitter.com/manikatex" title="twitter profile page of David Lafontant" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>
        </a>
      </li>
    </ul>
  </div>

app/views/layouts/_navbar.html.erb
<div class="flex-1 mx-2 hero-title text-site_gold">LAFONTANT</div>
<div class="flex-none hidden lg:block">
	<ul class="menu menu-horizontal">

				<li><%= link_to 'Home', root_path, :class => "py-4 px-2 text-site_light_gray" %></li>
				<li><%= link_to 'About', static_pages_about_path, :class => "py-4 px-2 text-site_light_gray"   %></li>
				<li><%= link_to 'Projects', static_pages_project_path,  :class => "py-4 px-2 text-site_light_gray"   %></li>
				<li><%= link_to 'Contact', new_contact_path, :class => "py-4 px-2 text-site_light_gray"   %></li>

	</ul>
</div>

app/views/layouts/_sidebar.html.erb
  <div class="drawer-side">
    <label for="my-drawer-3" class="drawer-overlay"></label> 
    <ul class="menu p-4 overflow-y-auto w-80 bg-cg_blue glass" >
      <li><%= link_to 'Home', root_path, :class => "py-4 px-2 text-site_light_gray" %></li>
      <li><%= link_to 'About', static_pages_about_path, :class => "py-4 px-2 text-site_light_gray"   %></li>
      <li><%= link_to 'Projects', static_pages_project_path,  :class => "py-4 px-2 text-site_light_gray"   %></li>
      <li><%= link_to 'Contact', new_contact_path, :class => "py-4 px-2 text-site_light_gray"   %></li>
    </ul>   
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
<%= stylesheet_link_tag "wind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="bg-site_dark_blue">

    <div class="drawer">
      <input id="my-drawer-3" type="checkbox" class="drawer-toggle" /> 
      <div class="drawer-content flex flex-col">
        <!-- Navbar -->
        <div class="w-full navbar px-10 ">
          <div class="flex-none lg:hidden">
            <label for="my-drawer-3" class="btn btn-square btn-ghost">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
            </label>
          </div> 
          <%= render 'layouts/navbar' %>
        </div>
        <div class="container text-site_light_gray">
          <br>
          <% flash.each do |key, message| %>
            <div class="alert alert-<%= key %>"><%= message %></div>
          <% end %>
        </div>

        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>

        <%= render 'layouts/sidebar' %>


    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="hero min-h-fit bg-site_dark_blue border-border">
  <div class="hero-content flex-col lg:flex-row-reverse">
    <%= image_tag("profile.jpg" , :class => "max-w-sm rounded-lg shadow-2xl") %>
    <div class="prose">
      <h1 class="text-4xl font-bold">Hello!  I'am David Lafontant</h1>
      <p class="py-6">
        I completed the Web development training of Microverse. I have thousands of hours in pair programming and remote collaboration. I used to work in global, fast-paced, and diverse environments. <br>
        I create web applications using programming languages and frameworks such as JavaScript, Node.js, React.js, Ruby, and Ruby on Rails. I have a solid foundation in data analysis with Excel, Python, and R.<br>
        From my 12 years of career in the Haitian public administration - which peaks as the head of the Statistic and planning department in CONATEL ( the Haitian telecom regulatory agency), I gained professional skills in team and time management, and public speaking, and negotiation. I am a polyglot who speaks English and french fluently. I am an avid reader and self-taught learner. I enjoy creative coding and am a generative art fan.<br>
        If you'd like to get in contact about potential opportunities, please reach out through my email: <a href="mailto: lafontant.david@gmail.com" class="no-underline hover:underline hover:bg-blue-700 visited:bg-secondary" title="Link to send an email to David Lafontant" target="_blank">lafontant.david@gmail.com</a>. You can also use the form on the contact page or click on any of the social media icons below.

      </p>

      <ul class="flex space-x-6 mb-4" id="contact">
        <li class="tooltip flex glass justify-center items-center p-4" data-tip="LinkedIn">
            <a href="https://www.linkedin.com/in/david-lafontant/" title="Linkedin profile page of David Lafontant" target="_blank" >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/></svg>
            </a>

        </li>
        <li class="tooltip flex glass justify-center items-center p-4"data-tip="WhatsApp">
            <a href="https://wa.me/18097599396" title="link to contact me on WhatsApp" target="_blank">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 59.7 94.8 83.8 35.2 15.2 49 16.5 66.6 13.9 10.7-1.6 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z"/></svg>
            </a>
        </li>
        <li class="tooltip flex glass justify-center items-center p-4" data-tip="Twitter">
            <a href="https://twitter.com/manikatex" title="twitter profile page of David Lafontant" target="_blank">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>
            </a>         

        </li>
      </ul>




            <button class="btn btn-primary">
      <%= link_to "Download Resume", static_pages_resume_path %>
      </button>
    </div>
  </div>
</div>


<div class="hero min-h-fit bg-site_dark_blue border-box">
  <div class="hero-content flex-col lg:flex-row ">
      <%= image_tag("pexels-miguel-a-padrinan-3785929.jpg" , :class => "brightness-50 max-w-sm rounded-lg shadow-2xl") %>
    <div class="prose">
      <h2 class="text-3xl font-bold text-white">Professional skills</h2>
      <ul>
          <li class="stack">Team management</li>
          <li class="stack">Communication</li>
          <li class="stack">Project management</li>
          <li class="stack">Time management</li>
          <li class="stack">Flexibility</li>
          <li class="stack">Public Speaking</li>
          <li class="stack">Remote programming</li>
          <li class="stack">Pair programming</li>
        </ul>
    </div>
  </div>
</div>

<div class="hero min-h-fit bg-site_dark_blue border-box">
  <div class="hero-content flex-col lg:flex-row">
    <%= image_tag("pexels-neo-2653362.jpg" , :class => "max-w-sm rounded-lg shadow-2xl") %>
    <div class="prose">
      <h2 class="text-3xl font-bold text-white">Tech stack</h2>
      <ul>
    
          <li class="stack" >React</li>
          <li class="stack" >Javascript</li>
          <li class="stack" >Git</li>
          <li class="stack" >Webpack</li>
          <li class="stack" >Ruby</li>
          <li class="stack" >Ruby on Rails</li>
          <li class="stack" >PostgresSQL</li>
          <li class="stack" >MySQL</li>
          <li class="stack" >Python</li>
          <li class="stack" >CSS3</li>
          <li class="stack" >SASS</li>
          <li class="stack" >Tailwind CSS</li>
          <li class="stack" >Bootstrap</li>
          <li class="stack" >Python</li>
          <li class="stack" >R</li>
          <li class="stack" >Neo4j</li>
          <li class="stack" >HTML5</li>
      </ul>
    </div>
  
  
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="hero min-h-screen bg-site_dark_blue">
  <div class="hero-content text-center">
    <div class="max-w-md ">
      <div class="avatar">
        <div class="w-24 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
          <%= image_tag("profile.jpg") %> 
        </div>
      </div>
        <h1 class="text-5xl hero-title font-bold text-site_gold">David Lafontant</h1>
        <p class="text-4xl text-site_light_gray hero-title">Full Stack Web Developer</p>
        <p class="hero-p text-white">Javascript, Ruby, PostgreSQL, Python and R</p>
        <p class="hero-p text-white">I am eager to help you solve your web development challenges!</p>
        <p class="btn btn-primary">
          <%= link_to "Download Resume", static_pages_resume_path %>      
        </p>
    </div>
  </div>
</div>

app/views/static_pages/project.html.erb
 <div class="flex justify-center">
  <div class="card shadow-xl m-0 border-box">
    <div class="card-body prose m-0 border-box">
      <h3 class="card-title m-0 text-center text-4xl hero-title font-bold">Projects</h3>
      <p class="m-0 p-0 border-box text-2xl">
        The projects below are my GitHub pinned projects. They have been built with 
        languages and frameworks such as JavaScript, Ruby, React, and Ruby on Rails. 
        By clicking their card you can read a short description of each of them and access 
        their respective repository.  
        <br>Feel free to visit my projects on <a href="https://github.com/david-lafontant" title="Github profile page of David Lafontant" target="_blank" class="no-underline badge badge-accent badge-outline"><strong>Github</strong></a> if you want to have a better view of my work and and technical skills.
        Your comments are welcome.
      </p>
    </div>
  </div>
</div>
<div >
<% @profile_data.each  do |item| %>
  <% item.each_value do |value|  %>
<div class="hero min-w-fit min-h-fit bg-site_dark_blue border-box ">
  <div class="hero-content flex-col lg:flex-row glass border-box">
    <img src="<%= value["openGraphImageUrl"]%>" alt="social preview of<%= value["name"] %>" class="max-w-sm rounded-lg shadow-2xl" >
    <div class="prose lg:prose-xl">
            <h2 class="text-4xl hero-title font-bold">
            <%= value["name"] %> 
            </h2>
            <p class="text-2xl">     
            <%= value["description"] %>         
            </p>
            <div class="card-actions justify-start">       
              <a href="<%= value["url"]%>"target="_blank" class="btn btn-primary no-underline text-white ring-2 ring-blue-500/50">See repository</a>
            </div>

    </div>
  </div>
</div>
  <% end %>
<% end %> 
</div>

app/views/static_pages/resume.html.erb
<div>
  <h1 class="font-bold text-4xl">StaticPages#resume</h1>
  <p>Find me in app/views/static_pages/resume.html.erb</p>
</div>